# Uncomment the next line to define a global platform for your project
source ‘https://github.com/CocoaPods/Specs.git'
platform :ios, ’9.0’
use_frameworks!

target 'PokeDex' do
	pod 'Alamofire', '~> 4.0'
end
